name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, windows-2016, ubuntu-18.04]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: npm install
      - name: Build
        run: npm run build
      - name: ZIP Linux
        if: matrix.os == 'ubuntu-18.04'
        run: cd dist && zip -r toa-datasync.zip linux-unpacked
      - name: Cleanup artifacts
        run: |
          npx rimraf "dist/!(*.exe|*.deb|*.zip|*.AppImage|*.dmg)"
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{matrix.os}}
          path: dist
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "dist/**"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
